config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'home#index'

  resources :home
  namespace :admin do
    namespace :products do
      post 'csv_upload'
    end
    resources :products do
      member do
        delete 'delete_image_attachment'
      end
    end
    resources :categories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
end

app/models/concerns/polite_validator.rb
class PoliteValidator < ActiveModel::EachValidator
  def validate_each(object, attribute, value)
    if value.to_s.downcase.include?('bad')
      object.errors.add(attribute, "contains word 'bad'")
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: { draft: 0, published: 1, archived: 2 }

  scope :long_title, ->(length = 15) { where('LENGTH(title) > ?', length) }
  scope :short_body, ->(length = 5) { where('LENGTH(description) < ?', length) }
  scope :search, ->(arg) { where('title LIKE ? or description LIKE ?', "%#{arg}%", "%#{arg}%") }

  has_one_attached :cover_image
  has_many_attached :images
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :stock, :price, numericality: { greater_than_or_equal_to: 0 }
  validates :title, :description, polite: true

  before_save :clean_data
  def clean_data
    self.title = title.upcase.squish
    self.description = description.humanize
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @categories = Category.all
    @products = @products.search(@search) if @search.present?
    @categories = @categories.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create(product_params)

    flash[:error] = @category.errors.full_messages if @category.invalid?

    redirect_to action: :index
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to action: :index
  end

  private

  def product_params
    params.require(:category).permit(:name, :description, :stock)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @products = Product.all
    @products = @products.search(@search) if @search.present?

    @products = @products.page(params[:page]).order(updated_at: :desc).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.create(product_params)

    flash[:error] = @product.errors.full_messages if @product.invalid?

    redirect_to action: :index
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to action: :index
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(',').map(&:strip)
      Product.create title: attr[0], description: attr[1], stock: attr[2], price: attr[3]
    end
    redirect_to action: :index
  end

  private

  def generate_csv(articles)
    articles.map { |a| [a.title, a.description, a.stock, a.price, a.created_at.to_date].join(',') }.join("\n")
  end

  def product_params
    params.require(:product).permit(:title, :description, :cover_image, :stock, :price, :status, images: [],
                                                                                                 category_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @categories = Category.all
    if @search.present?
      @categories = @categories.where('title LIKE ? or body LIKE ?', "%#{@search}", "%#{@search}").page(@search).per(5)
    end
    @categories = @categories.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create(product_params)

    flash[:error] = @category.errors.full_messages if @category.invalid?

    redirect_to action: :index
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to action: :index
  end

  private

  def product_params
    params.require(:category).permit(:name, :description, :stock)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @products = @products.search(@search) if @search.present?

    @products = @products.page(params[:page]).order(updated_at: :desc).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @products = Product.all
    @products = @products.search(@search) if @search.present?

    @products = @products.page(params[:page]).order(updated_at: :desc).per(10)

    respond_to do |format|
      format.html
      format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.create(product_params)

    flash[:error] = @product.errors.full_messages if @product.invalid?

    redirect_to action: :index
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to action: :index
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to action: :index
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(',').map(&:strip)
      Product.create title: attr[0], description: attr[1], stock: attr[2], price: attr[3]
    end
    redirect_to action: :index
  end

  private

  def generate_csv(articles)
    articles.map { |a| [a.title, a.description, a.stock, a.price, a.created_at.to_date].join(',') }.join("\n")
  end

  def product_params
    params.require(:product).permit(:title, :description, :cover_image, :stock, :price, :status, images: [],
                                                                                                 category_ids: [])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/categories/_form.slim
= form_with model: [:admin, category] do |f|
  div = f.text_field :name, placeholder: 'Name'
  div = f.text_area :description, placeholder: 'Write content here'
  div = f.submit 'Submit Category', class: 'btn btn-outline-primary'

app/views/admin/categories/edit.slim
h1 Edit new category

div
  = link_to admin_categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', category: @category

app/views/admin/categories/index.slim
.row
  .col-6
    h1 This is categories list
  .col-6
    .float-right
      - if current_admin
        div = current_admin.email
        div = link_to 'Logout', destroy_admin_session_path, method: :delete
      - else
        div = link_to 'Login', new_admin_session_path

.row
  .col
    = form_tag admin_categories_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'type something here', class: 'form-control'

.row.mt-2
  .col-12
    = link_to admin_products_path do
      = button_tag 'Product', class: 'btn btn-primary'
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Name
          th Description
          th Created at
          th Updated at
          th Action
      tbody
        - @categories.each do |a|
          tr
            td = a.id
            td = a.name
            td = a.description
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to admin_category_path(a) do
                i.fas.fa-eye
              - if current_admin
                span.ml-3
                  = link_to edit_admin_category_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to admin_category_path(a), method: :delete do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @categories
  - if current_admin
    .col-6
      .float-right
        = link_to new_admin_category_path do
          = button_tag 'Add new Category', class: 'btn btn-primary'

app/views/admin/categories/new.slim
h1 Add new category

div
  = link_to admin_categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', category: @category

app/views/admin/categories/show.slim
h1 = @category.name
hr
div = @category.description
div
  = link_to admin_categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
hr

app/views/admin/products/_form.slim
= form_with model: [:admin, product] do |f|
  label Cover Image
  div
    - if @product.cover_image.attached?
      span
        = image_tag @product.cover_image, width: '500px'
      span.ml-2
        = link_to 'Delete image', delete_image_attachment_admin_product_path(@product.cover_image.id), method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
    - else
      = f.file_field :cover_image
  label Title
  div = f.text_field :title, placeholder: 'Title'
  label Description
  div = f.text_area :description, placeholder: 'Write content here'
  label Stock
  div = f.number_field :stock, placeholder: 'Insert Stock number', min: 0
  label Price
  div = f.number_field :price, placeholder: 'Price', min: 0
  label Category
  div = f.collection_check_boxes :category_ids, Category.all, :id, :name
  label Status
  div = f.select :status, Product.statuses.keys
  label Images
  - if @product.images.attached?
    - @product.images.each do |image|
      div
        span
          = image_tag image, width: '80px'
        span.ml-2
          = link_to 'Delete Image', delete_image_attachment_admin_product_path(image.id), method: :delete,
                  data: { confirm: 'Are you sure to delete the preview' }, class: 'btn btn-danger'
  div = f.file_field :images, multiple: true

  div = f.submit 'Submit Product', class: 'btn btn-outline-primary'

  link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css"
  script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"

  javascript:
      // Later
      document.addEventListener("turbolinks:load", function () {
          if (document.getElementsByClassName("editor-toolbar").length === 0)
          let editor = new SimpleMDE({element: document.getElementById('product_description')});
      })

app/views/admin/products/edit.slim
h1 Edit new product

div
  = link_to admin_products_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
= render 'form', product: @product

app/views/admin/products/index.slim
ruby:
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)

.row
  .col-6
    h1 This is products list
  .col-6
    .float-right
      - if current_admin
        div = current_admin.email
        div = link_to 'Logout', destroy_admin_session_path, method: :delete
      - else
        div = link_to 'Login', new_admin_session_path

.row
  .col-10
    = form_tag admin_products_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
  .col-2
    = link_to admin_products_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'

.row.mt-2
  .col-12
    = link_to admin_categories_path do
      = button_tag 'Category', class: 'btn btn-primary'
    table.table.table-hover
      thead.thead-dark
        tr
          th Cover
          th Status
          th Title
          th Description
          th Number of stocks
          th Categories
          th Images
          th Created at
          th Updated at
          th Action
      tbody
        - @products.each do |p|
          tr
            td
              - if p.cover_image.attached?
                = image_tag p.cover_image, width: '64px'
            td = p.status
            td.font-weight-bold = p.title.first(16)
            td = raw markdown.render(p.description)
            td = p.stock
            td = p.categories&.map(&:name)&.join(',').presence || 'NA'
            td
              - p.images.each do |image|
                = image_tag image, width: '32px'
            td.font-weight-light = "#{time_ago_in_words(p.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(p.updated_at.to_date)} Ago"
            td
              span
              = link_to admin_product_path(p) do
                i.fas.fa-eye
              - if current_admin
                span.ml-3
                  = link_to edit_admin_product_path(p) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to admin_product_path(p), method: :delete do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @products
  .col-6
    .float-right
      - if current_admin
        = link_to new_admin_product_path do
          = button_tag 'Add new Product', class: 'btn btn-outline-primary'

div
  hr

.row
  .col
    = form_tag admin_products_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/admin/products/new.slim
h1 Add new product

div
  = link_to admin_products_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', product: @product

app/views/admin/products/show.slim
h1 = @product.title
hr
div
  - if @product.cover_image.attached?
    = image_tag @product.cover_image, width: '1000px'
div = @product.description
div
  - @product.images.each do |image|
    = image_tag image, width: '400px'
div
  = link_to admin_products_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
hr
/ hr
/   h2 Comments Section
/   div
/     - @product.comments.each do |comment|
/       div
/         = "#{comment.author} Wrote : #{comment.text}"
/ hr
/   h2 Add new Comment Section
/   =form_with model: [@product, @product.comments.build] do |f|
/     div = f.text_field :author, placeholder: 'Author'
/     div = f.text_area :text, placeholder: 'Write text here'
/     div = f.submit 'Submit Comment'

app/views/categories/_form.slim
= form_with model: @category do |f|
  div = f.text_field :name, placeholder: 'Name'
  div = f.text_area :description, placeholder: 'Write content here'
  div = f.submit 'Submit Category', class: 'btn btn-outline-primary'

app/views/categories/edit.slim
h1 Edit new category

div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', category: @category

app/views/categories/index.slim
.row
  .col-6
    h1 This is categories list
  .col-6
    .float-right
      - if current_admin
        div = current_admin.email
        div = link_to 'Logout', destroy_admin_session_path, method: :delete
      - else
        div = link_to 'Login', new_admin_session_path

.row
  .col
    = form_tag categories_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'type something here', class: 'form-control'

.row.mt-2
  .col-12
    = link_to products_path do
      = button_tag 'Product', class: 'btn btn-primary'
    table.table.table-hover
      thead.thead-dark
        tr
          th ID
          th Name
          th Description
          th Created at
          th Updated at
          th Action
      tbody
        - @categories.each do |a|
          tr
            td = a.id
            td = a.name
            td = a.description
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to category_path(a) do
                i.fas.fa-eye
              - if current_admin
                span.ml-3
                  = link_to edit_category_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to category_path(a), method: :delete do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @categories
  - if current_admin
    .col-6
      .float-right
        = link_to new_category_path do
          = button_tag 'Add new Category', class: 'btn btn-primary'

app/views/categories/new.slim
h1 Add new category

div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', category: @category

app/views/categories/show.slim
h1 = @category.name
hr
div = @category.description
div
  = link_to categories_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
hr

app/views/home/index.slim
.products
  h1.lg-title Commerce Website
  p.text-light-home This is my commerce website
  .row
    .col-10
      = form_tag admin_products_path, method: :get do
        = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
    .col-2
      = link_to admin_products_path(format: :csv) do
        = button_tag 'Download CSV', class: 'btn btn-secondary float-right'
  .row.mt-2
    .col-12
      = link_to admin_products_path do
        = button_tag 'Admin Page', class: 'btn btn-outline-primary'

  .product-items.flex
    - @products.each do |p|
      .product
        .product-content
          .product-img
            - if p.cover_image.attached?
              = image_tag p.cover_image, alt: 'product image'
          .product-btns
            button.btn-cart type="button"
              label.btn-text
                | add to cart
              span
                i.fas.fa-plus
            button.btn-buy type="button"
              label.btn-text
                | buy now
              span
                i.fas.fa-shopping-cart
        .product-info
          .product-info-top
            h2.sm-title lifestyle
          / Describe item section
          = link_to p.title, admin_product_path(p), class: 'product-name'
          p.product-price
            = p.price
            | ฿

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Myapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <h1 style="color: red">
    <%= flash[:error]&.join(', ') %>
  </h1>
  <%= yield %>

  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.5.1.slim.min.js' %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' %>
</div>
</body>
</html>

app/views/products/edit.slim
h1 Edit new product

div
  = link_to products_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
br
  = render 'form', product: @product

app/views/products/index.slim
.row
  .col-6
    h1 This is products list
  .col-6
    .float-right
    - if current_admin
      div = current_admin.email
      div = link_to 'Logout', destroy_admin_session_path, method: :delete
    - else
      div = link_to 'Login', new_admin_session_path

.row
  .col-10
    = form_tag products_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
  .col-2
    = link_to products_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'

.row.mt-2
  .col-12
    = link_to categories_path do
      = button_tag 'Category', class: 'btn btn-primary'
    table.table.table-hover
      thead.thead-dark
        tr
          th Cover
          th Status
          th Title
          th Description
          th Number of stocks
          th Categories
          th Images
          th Created at
          th Updated at
          th Action
      tbody
        - @products.each do |a|
          tr
            td
              - if a.cover_image.attached?
                = image_tag a.cover_image, width: '64px'
            td = a.status
            td.font-weight-bold = a.title.first(16)
            td = a.description
            td = a.stock
            td = a.categories&.map(&:name)&.join(',').presence || 'NA'
            td
              - a.images.each do |image|
                = image_tag image, width: '32px'
            td.font-weight-light = "#{time_ago_in_words(a.created_at.to_date)} Ago"
            td.font-weight-light = "#{time_ago_in_words(a.updated_at.to_date)} Ago"
            td
              span
              = link_to product_path(a) do
                i.fas.fa-eye
              - if current_admin
                span.ml-3
                  = link_to edit_product_path(a) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to product_path(a), method: :delete do
                    i.fas.fa-trash

.row
  .col-6
    = paginate @products
  .col-6
    .float-right
      - if current_admin
        = link_to new_product_path do
          = button_tag 'Add new Product', class: 'btn btn-outline-primary'

div
  hr

.row
  .col
    = form_tag products_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/products/index_old.slim
.row
  .col-6
    h1 This is products list
  .col-6
    .float-right
    - if current_admin
      div = current_admin.email
      div = link_to 'Logout', destroy_admin_session_path, method: :delete
    - else
      div = link_to 'Login', new_admin_session_path

.row
  .col-10
    = form_tag products_path, method: :get do
      = text_field_tag 'search', @search, placeholder: 'Type something', class: 'form-control'
  .col-2
    = link_to products_path(format: :csv) do
      = button_tag 'Download CSV', class: 'btn btn-secondary float-right'

.row.mt-2
  .col-12
    = link_to categories_path do
      = button_tag 'Category', class: 'btn btn-primary'
    .product-items
      - @products.each do |p|
        .product
          .product-content
            .product-img
              - if p.cover_image.attached?
                = image_tag p.cover_image, alt: 'product image'
            .product-btns
              button.btn-cart type="button"
                label.btn-text
                  | add to cart
                span
                  i.fas.fa-plus
              button.btn-buy type="button"
                label.btn-text
                  | buy now
                span
                  i.fas.fa-shopping-cart
          .product-info
            .product-info-top
              h2.sm-title lifestyle
            / Describe item section
            = link_to p.title, product_path(p), class: 'product-name'
            p.product-price
            p.product-price
              = p.price
              | ฿
          / .off-info
          /   h2.sm-title 25% off

.row
  .col-6
    = paginate @products
  .col-6
    .float-right
      - if current_admin
        = link_to new_product_path do
          = button_tag 'Add new Product', class: 'btn btn-outline-primary'

div
  hr

.row
  .col
    = form_tag products_csv_upload_path, multipart: true do
      div = file_field_tag :csv_file
      div = submit_tag :upload

app/views/products/show.slim
h1 = @product.title
hr
div
  - if @product.cover_image.attached?
    = image_tag @product.cover_image, width: '1000px'
div = @product.description
div
  - @product.images.each do |image|
    = image_tag image, width: '400px'
div
  = link_to products_path do
    = button_tag 'Back', class: 'btn btn-outline-primary'
hr
/ hr
/   h2 Comments Section
/   div
/     - @product.comments.each do |comment|
/       div
/         = "#{comment.author} Wrote : #{comment.text}"
/ hr
/   h2 Add new Comment Section
/   =form_with model: [@product, @product.comments.build] do |f|
/     div = f.text_field :author, placeholder: 'Author'
/     div = f.text_area :text, placeholder: 'Write text here'
/     div = f.submit 'Submit Comment'